# Generated by Django 3.1.3 on 2020-11-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201115_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productsinorder',
            name='sum',
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='productsinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_to_order', to='api.order', verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='productsinorder',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='количество товара'),
        ),
    ]
